language: cpp
compiler:
  - gcc
  - clang
env:
  - FFMPEG=git://git.videolan.org/ffmpeg.git
  - FFMPEG=git://git.libav.org/libav.git
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8
install:
  - sudo apt-get install yasm
  - git clone $FFMPEG --depth=1 ffmpeg
  - cd ffmpeg
  - ./configure --disable-avfilter --disable-devices --disable-doc --disable-encoders --disable-filters --disable-hwaccels --disable-muxers --disable-network
  - make -j2
  - sudo make install
  - cd ..
script:
  - ./configure --extra-cxxflags='-Werror' || cat config.log
  - make V=1 -j2 -k
notifications:
  email:
    - on_success: change
    - on_failure: change
